### ISSUE TITLE
设置config.namespace后，黑白名单规则获取失败。

### ISSUE THREAD

**Issue by WhaleCloud-platform** [apache/dubbo#4469] opened 2019-07-04 11:24 UTC
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.2
* Operating System version: mac
* Java version: JDK8

### Steps to reproduce this issue

```java
ConfigCenterConfig.java
    @Parameter(key = CONFIG_NAMESPACE_KEY, useKeyAsProperty = false)
    public String getNamespace() {
        return namespace;
    }
```
```java
AbstractConfig.java
      Parameter parameter = method.getAnnotation(Parameter.class);
      if (parameter != null && parameter.key().length() > 0 && parameter.useKeyAsProperty()) {
               key = parameter.key();
       } else {
              key = prop;
       }
```
```java
ZookeeperDynamicConfiguration.java
rootPath = "/" + url.getParameter(CONFIG_NAMESPACE_KEY, DEFAULT_GROUP) + "/config";
```
#### 问题
> 在dubbo-admin中定义了黑白名单，设置了分组`admin.registry.group=henry1`，保存到zk`/root/henry1/config`下

> 设置属性`dubbo.config-center.group=henry1
dubbo.config-center.namespace=henry1` consumer端启动，但是在`ZookeeperDynamicConfiguration`取出来的值发现是`dubbo`，导致规则获取失败。

#### 原因
> 因为`getNamespace`的`useKeyAsProperty`为false，在`AbstractConfig`解析时取的key为`namespace`不是`config.namespace`。在`ZookeeperDynamicConfiguration`取`CONFIG_NAMESPACE_KEY`为NULL

> 是否需要把`getNamespace`的`useKeyAsProperty`改为true，或者是修改`ZookeeperDynamicConfiguration`的取值key

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

> 希望在`ZookeeperDynamicConfiguration`可以获取到值，而不是默认值

**Comment by chickenlj** [comment] 2019-07-08 01:17
Thanks for the report, it will be fixed in 2.7.3.

duplicate of https://github.com/apache/dubbo/issues/3872

**Closed by chickenlj** 2019-07-08 01:17 UTC
