### ISSUE TITLE
In telnet, typing special characters causes no response, and the client cannot run or quit.

### ISSUE THREAD

**Issue by Helltab** [apache/dubbo#13812] opened 2024-03-01 02:14 UTC
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.6
* Operating System version: macos 14
* Java version: jdk21

### Steps to reproduce this issue
Describe: When type 'ctrl + c', telnet get '^c' and the client cannot run or quit.
Excepted result: quit or prompt 'no such command'
![image](https://github.com/apache/dubbo/assets/26338738/80f84ba2-6ccc-40ed-a03c-19daaf61db89)
![image](https://github.com/apache/dubbo/assets/26338738/45c0ad6c-dd03-4ef8-b4a5-10b9ab56c3c0)

**Comment by AlbumenJ** [comment] 2024-03-06 01:54
Can you please try to enhance it?

**Comment by AlbumenJ** [comment] 2024-03-06 01:55
The problem is caused by `org/apache/dubbo/qos/server/handler/QosProcessHandler.java:92`

**Comment by hengyoush** [comment] 2024-03-06 02:26
I can try solve it , please assign it to me.

**Closed as completed** 2024-03-22 12:54 UTC
Labels: help wanted, type/enhancement, component/sdk
