### ISSUE TITLE
[Bug] Dubbo 3.3.x Call-Chain of Skywalking not correct

### ISSUE THREAD

**Issue by ldcsaa** [apache/dubbo#14925] opened 2024-11-23 01:41 UTC
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo 3.3.x

### Steps to reproduce this issue

While applications upgrade to Dubbo 3.3.x , the Call-Chain of consumer & provider would break .

Just start Dubbo 3.3.x consumer & provider , and invoke make any remote call , then watch the skywalking-ui topology graph .

The actual call-chain is: `User` -> `hp-demo-buff-skywalking` -> `hp-demo-infra-skywalking-service`
![image](https://github.com/user-attachments/assets/41a5dcb5-c513-404d-9e5f-09872e4b6ca5)

### What you expected to happen

Call-Chain would not break .

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment] 2024-11-25 02:05
Please submit issue to Skywalking first

**Comment by ldcsaa** [comment] 2024-11-25 06:22
> Please submit issue to Skywalking first

This is the answer of Skywalking:
https://github.com/apache/skywalking/issues/12791

**Comment by wxbty** [comment] 2024-12-03 03:44
@ldcsaa   When I tried to reproduce your example, the same error occurred at first, but after waiting for two minutes and refreshing the page, I got the correct result. Please confirm whether your example is the same. If so, a short-term status error in the middle should be acceptable.    
![image](https://github.com/user-attachments/assets/b664f2ff-4832-4b00-ba0f-6e2196d434ca)

**Comment by wxbty** [comment] 2024-12-03 08:50
I have reproduced your problem using the latest version. The cause has been found and may be fixed in subsequent versions. You can temporarily use the following configuration to solve it:    
dubbo:
  consumer:
    filter: -observationsender

**Comment by ldcsaa** [comment] 2024-12-03 18:39
> I have reproduced your problem using the latest version. The cause has been found and may be fixed in subsequent versions. You can temporarily use the following configuration to solve it: dubbo: consumer: filter: -observationsender

I had tried, it does work:
![image](https://github.com/user-attachments/assets/c157179f-5b86-42d4-8994-e45334fb9f73)

**Closed as completed** 2024-12-10 07:45 UTC
Labels: type/need-triage, component/need-triage
