### ISSUE TITLE
Dubbo 2.7.0 DubboComponentScan cause NullPointerException 

### ISSUE THREAD

**Issue by seishuchen** [apache/dubbo#4250] opened 2019-06-05 02:10 UTC
- [  ✔ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ✔ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0
* Operating System version: MAC
* Java version: JDK1.8

### Steps to reproduce this issue

1. new a spring boot project with dubbo 2.7.0
2. new Dubbo Service
3. use org.apache.dubbo.config.spring.context.annotation.DubboComponentScan
4. run or debug

PS: replace  `org.apache.dubbo.config.spring.context.annotation.DubboComponentScan` with `org.springframework.context.annotation.ComponentScan` or `org.apache.dubbo.config.spring.context.annotation.CompatibleDubboComponentScan` ,
then it will work normally.

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

the dubbo service export success and keep alive with zookeeper.

### Actual Result

org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.initReferenceBeanInvocationHandler will throw an NullPointerException, then destroy zookeeper registry

```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2019-06-05 09:58:13.773 ERROR org.springframework.boot.SpringApplication Line:771 - Application startup failed
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106)
	at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.initReferenceBeanInvocationHandler(ReferenceAnnotationBeanPostProcessor.java:232)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.onServiceBeanExportEvent(ReferenceAnnotationBeanPostProcessor.java:226)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.onApplicationEvent(ReferenceAnnotationBeanPostProcessor.java:218)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.apache.dubbo.config.spring.ServiceBean.publishExportEvent(ServiceBean.java:328)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:320)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:112)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:58)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.guahao.dime.service.DimeApplication.main(DimeApplication.java:24)
2019-06-05 09:58:13.785 INFO  org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext Line:984 - Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@496a31da: startup date [Wed Jun 05 09:57:55 CST 2019]; root of context hierarchy
2019-06-05 09:58:13.791 INFO  org.apache.dubbo.registry.support.AbstractRegistryFactory Line:66  -  [DUBBO] Close all registries [zookeeper://192.168.99.51:2183/org.apache.dubbo.registry.RegistryService?application=dime-service&backup=192.168.99.37:2183&dubbo=2.0.2&interface=org.apache.dubbo.registry.RegistryService&pid=2022&release=2.7.0&timestamp=1559699887707], dubbo version: 2.7.0, current host: 220.250.64.20
2019-06-05 09:58:13.793 INFO  org.apache.dubbo.registry.zookeeper.ZookeeperRegistry Line:66  -  [DUBBO] Destroy registry:zookeeper://192.168.99.51:2183/org.apache.dubbo.registry.RegistryService?application=dime-service&backup=192.168.99.37:2183&dubbo=2.0.2&interface=org.apache.dubbo.registry.RegistryService&pid=2022&release=2.7.0&timestamp=1559699887707, dubbo version: 2.7.0, current host: 220.250.64.20
```

**Comment by CrazyHZM** [comment] 2019-06-05 03:27
Can you provide related configuration or annotations?

**Comment by tswstarplanet** [comment] 2019-06-05 05:02
I have a look the code, it is because the service bean does not have serviceBeanName.

**Comment by tswstarplanet** [comment] 2019-06-05 07:02
You can try @EnableDubbo annotation instead of using @DubboComponentScan directly

**Comment by seishuchen** [comment] 2019-06-05 13:53
> EnableDubbo

YES，the serviceBeanName is null, now We just use other annotations instead of @DubboComponentScan, but our company has too many applications,  in order to reduce modification as much as possible，I hope apache dubbo team to fix this issue。

**Comment by tswstarplanet** [comment] 2019-06-06 02:29
Would you please provide a demo to reproduce this problem on github ?

**Comment by cvictory** [comment] 2019-09-04 09:10
@seishuchen  What about this issue now?

**Comment by cvictory** [comment] 2019-09-09 06:04
I will close this issue. If you still have this issue, please reopen this issue.

**Closed by cvictory** 2019-09-09 06:04 UTC
