### ISSUE TITLE
RpcContext's ServerContext can not transform data from provider to consumer when using sync invoke mode

### ISSUE THREAD

**Issue by tswstarplanet** [apache/dubbo#3662] opened 2019-03-14 16:46 UTC
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.x
* Operating System version: MacOS
* Java version: 1.8

### Steps to reproduce this issue

1. Execute following code in a method of a dubbo service on provider side:
```java
RpcContext.getServerContext().setAttachment("abc", "123");
```
2. Execute following code in the same thread that invoke the remote dubbo service after the invoking:
```java
Map<String, String> map = RpcContext.getServerContext().getAttachments();
System.out.println("context: " + map.get("abc"));
```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

Console output:
context: 123

### Actual Result
context: null

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by tswstarplanet** [comment] 2019-03-14 16:53
#3664

**Comment by carryxyh** [comment] 2019-03-15 02:20
I think your pr will cause new problems. 
@chickenlj  Would you like to check this pr twice?

By the way, why create a new issue. Focus on https://github.com/apache/incubator-dubbo/issues/3620?

**Comment by tswstarplanet** [comment] 2019-03-15 02:47
Because this pr cannot solve the problem when using async invoke

**Comment by carryxyh** [comment] 2019-03-15 02:49
But it will cause another problem.
Pls check my comment under your pr.

**Comment by tswstarplanet** [comment] 2019-03-15 02:50
I am not sure if the remove operation of servercontext that is execute in the onResponse method is equal to be executed in the invoke method.

**Comment by carryxyh** [comment] 2019-03-15 02:53
of course not.... 
The two are not equal..

Since this pr can't fix the problem, I think we can close this issue and focus on https://github.com/apache/incubator-dubbo/issues/3620. What do u think

**Comment by tswstarplanet** [comment] 2019-03-15 02:55
I think it is two problems, one is sync invoke, the other is async. We can remains them both, or merge to one

**Comment by carryxyh** [comment] 2019-03-15 02:59
Maybe merge to one is better. We can change the title of https://github.com/apache/incubator-dubbo/issues/3620 to indicate there are some problems on server context.

**Comment by tswstarplanet** [comment] 2019-03-15 03:25
ok, and the description of sync invoke can be migrated to that one

**Comment by tswstarplanet** [comment] 2019-03-15 03:26
OK

**Comment by carryxyh** [comment] 2019-03-15 03:33
hi, @tswstarplanet 
I'd like close this issue and pr.
Maybe we need more discuss with it.

**Comment by tswstarplanet** [comment] 2019-03-15 03:36
I think the pr can be remained. It need some time to test ifit can solve the problem when using sync invoke without impacting async invoke. We donnot need to close one pr so quickly

**Comment by cvictory** [comment] 2019-05-06 07:50
http://dubbo.apache.org/zh-cn/docs/user/demos/attachment.html

I remember the attachment value is transfered from consumer to provider but not provider to consumer.

**Comment by chickenlj** [comment] 2020-02-02 05:17
I tried both sync and async invoke on 2.7.5, failed to reproduce, I think this issue does not exist or it's been fixed.

**Closed by chickenlj** 2020-02-02 05:17 UTC
