### ISSUE TITLE
dubbo-registry-nacos 0.0.2 can't load com.alibaba.dubbo.registry.nacos.NacosRegistryFactory

### ISSUE THREAD

**Issue by slievrly** [apache/dubbo#3467] opened 2019-02-13 10:03 UTC
![image](https://user-images.githubusercontent.com/8758457/52703240-da08ab80-2fb8-11e9-8a74-0ad59060358d.png)
![image](https://user-images.githubusercontent.com/8758457/52703293-03293c00-2fb9-11e9-9991-3ab54a123bbe.png)
![image](https://user-images.githubusercontent.com/8758457/52703337-1cca8380-2fb9-11e9-8940-c1c0065ff132.png)

dubbo-registry-nacos 0.0.2 + org.apache.dubbo 2.7.0 
dubbo-registry-nacos 0.0.2 required com.alibaba.dubbo.registry.support.AbstractRegistryFactory
but in org.apache.dubbo 2.7.0 jar found  org.apache.dubbo.registry.support.AbstractRegistryFactory

**Comment by chickenlj** [comment] 2019-12-18 14:32
> dubbo-registry-nacos 0.0.2 + org.apache.dubbo 2.7.0

Looks like `dubbo-registry-nacos 0.0.2` can not work with  2.7.0

**Comment by chickenlj** [comment] 2019-12-18 14:33
Mercy may know the compatible version of dubbo-registry-nacos

**Comment by chickenlj** [comment] 2019-12-18 14:34
duplicate of https://github.com/apache/dubbo/issues/3880 and https://github.com/apache/dubbo/issues/3791

**Comment by mercyblitz** [comment] 2020-04-21 07:52
Please use the `dubbo-registry-nacos` binding in the dubbo 2.7 +

**Closed by mercyblitz** 2020-04-21 07:52 UTC
