### ISSUE TITLE
dubbo monitorservice  (called by a slow provider instance or bad service implementation)

### ISSUE THREAD

**Issue by Hulk904** [apache/dubbo#7609] opened 2021-04-23 11:02 UTC
### Environment
* Dubbo version: 2.7.10
* Java version: jdk8
###dubbo monitor config
use dubbo.monitor.protocol=registry
return  2181 port(the regist center port, not monitorservice provider port) , while call MonitorService return error  (we implement MonitorService and regist as  dubbo service)
```
Caused by: java.lang.IllegalStateException: Consumer is shutting down and this call is going to be stopped without receiving any result, usually this is called by a slow provider instance or bad service implementation.
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.shutdownNow(ThreadlessExecutor.java:166)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.closeChannel(DefaultFuture.java:147)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.disconnected(HeaderExchangeHandler.java:134)
	at org.apache.dubbo.remoting.transport.AbstractChannelHandlerDelegate.disconnected(AbstractChannelHandlerDelegate.java:48)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:73)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41
```

use  dubbo.monitor.address=10.3.246.180:20885
ok  
20885 is the dubbo provider port .

**Comment by xiaoheng1** [comment] 2021-04-30 01:07
can you provider a demo to reproduce ?

**Comment by Hulk904** [comment] 2021-04-30 02:50
> can you provider a demo to reproduce ?
we just implement MonitorService, and the consumer can‘t find it. i think  use  dubbo.monitor.protocol=registry , the consumer can't get the right server url.

**Comment by xiaoheng1** [comment] 2021-04-30 03:13
Is the registry that implements the MonitorService connection and the registry of provider registration the same?

**Comment by Hulk904** [comment] 2021-04-30 03:26
> Is the registry that implements the MonitorService connection and the registry of provider registration the same?
yes, only one registry.

**Comment by Hulk904** [comment] 2021-04-30 03:28
> > Is the registry that implements the MonitorService connection and the registry of provider registration the same?
> > yes, only one registry.
We upgraded  dubbo from 2.7.7 to 2.7.10,  and it not working.

**Comment by asasas234** [comment] 2021-05-14 03:12
我们也遇到了这个问题，没人解决吗？

**Comment by xiaoheng1** [comment] 2021-05-14 03:23
can you provider a demo to reproduce it? My local test did not reproduce this problem

**Comment by xiaoheng1** [comment] 2021-05-14 03:24
you can upload the reproduced demo to github, I will checkout it and run.

**Comment by asasas234** [comment] 2021-05-14 03:30
现象就是我们从2.7.8 升级到2.7.10 就报了这个错误，配置方式就是dubbo.monitor.protocol = registry ,在2.7.10 能解决这个问题的办法，也就是楼上说的，只能在dubbo.monitor.address 配死地址

**Comment by asasas234** [comment] 2021-05-14 03:32
升级2.7.10 以后，我通过反射拿到MonitorService 直接调collect方法就会报错，但是2.7.8没事

**Comment by xiaoheng1** [comment] 2021-05-14 03:38
i will check the code later.

**Comment by asasas234** [comment] 2021-05-14 04:36
@xiaoheng1 我本地复现了这个问题，初步看是2.7.8 走了AbstractClusterInvoker ，然后把dubbo://zk的域名通过list方法转成了具体的Invoke list ,但是2.7.10 压根没走这个类

**Comment by xiaoheng1** [comment] 2021-05-14 06:58
I used dubbo2.7.10 to test and no problems were found. You can download dubbo-samples-monitor to test

**Comment by asasas234** [comment] 2021-05-14 07:20
@xiaoheng1 
`public static void main(String[] args) {
        URL url = URL.valueOf("dubbo://zk1.neibu.koolearn.com:2181/org.apache.dubbo.registry.RegistryService?application=koo-jwyth-express-manage&backup=zk2.neibu.koolearn.com:2181,zk3.neibu.koolearn.com:2181&dubbo=2.0.2&file=/Users/lizhibo/dubbo-cache/koo-jwyth-express-manage/dubbo.cache&id=org.apache.dubbo.config.RegistryConfig#0&logger=slf4j&pid=51140&protocol=registry&qos.enable=false&refer=application%3Dkoo-jwyth-express-manage%26dubbo%3D2.0.2%26interface%3Dorg.apache.dubbo.monitor.MonitorService%26logger%3Dslf4j%26pid%3D51140%26qos.enable%3Dfalse%26register.ip%3D10.155.8.180%26release%3D2.7.10%26timestamp%3D1620975048567&registry=zookeeper&release=2.7.10&timeout=10000&timestamp=1620975042327");
        System.out.println(url);
    }`

我可以复现了，我最终定位是URL 类的BUG，2.7.8 可以解析这个URL的protocol参数，但是2.7.10 给丢了

**Comment by asasas234** [comment] 2021-05-14 07:22
@xiaoheng1 因为这里把protocol 给丢了，所以在DubboMonitorFactory 创建Monitor的时候，取不到protocol参数，走的默认dubbo 协议，而不是RegistryProtocol

**Comment by asasas234** [comment] 2021-05-14 07:27
@xiaoheng1 你可以直接复制我上面的代码，跑下main方法，对比下2个版本的差异

**Comment by xiaoheng1** [comment] 2021-05-14 07:29
ok, i will test it.

**Comment by xiaoheng1** [comment] 2021-05-14 07:35
Can you provide the parameter configuration you monitor? 
I don’t think this is a URL problem. Because the protocol in the monitor is passed through the protocol parameter.

**Comment by xiaoheng1** [comment] 2021-05-14 07:42
Sorry, I missed some information, I will check this in detail

**Comment by xiaoheng1** [comment] 2021-05-14 07:52
@asasas234 this has been fixed with #7716

**Comment by asasas234** [comment] 2021-05-14 08:59
@xiaoheng1 这个是会合到哪个版本里去？啥时候发新版

**Comment by xiaoheng1** [comment] 2021-05-14 09:05
> @xiaoheng1 这个是会合到哪个版本里去？啥时候发新版

 This pr is currently in the master branch, and the next version will contain this pr.

**Closed** 2021-05-16 12:50 UTC
