### ISSUE TITLE
dubbo 2.7.9 无法注册到zk上去

### ISSUE THREAD

**Issue by jeesk** [apache/dubbo#7238] opened 2021-02-22 14:25 UTC
### Environment

* Dubbo dubbo 2.7.9
* Operating System version: window 10
* java version "1.8.0_191"

### Steps to reproduce this issue

1. zookeeper 版本  3.6.2-bin  (https://mirrors.tuna.tsinghua.edu.cn/apache/zookeeper/zookeeper-3.6.2/apache-zookeeper-3.6.2-bin.tar.gz)
zk 配置
```tickTime=2000
initLimit=10
syncLimit=5
dataDir=C:\\openSource\\apache-zookeeper-3.6.2-bin\\data
dataLogDir=C:\\openSource\\apache-zookeeper-3.6.2-bin\\log
clientPort=2181
audit.enable=true
admin.serverPort=9991

```

2.  当我运行dubbo-demo-annotation-provider 的org.apache.dubbo.demo.provider.Application#main 时候, 打印日志如下, 并没有报错
```
Connected to the target VM, address: '127.0.0.1:53362', transport: 'socket'
[22/02/21 22:23:29:481 CST] main  INFO logger.LoggerFactory: using logger: org.apache.dubbo.common.logger.log4j.Log4jLoggerAdapter
```
3.  运行 dubbo-demo-annotation-consumer 的 org.apache.dubbo.demo.consumer.Application#main, 报错
```
Exception in thread "main" java.lang.NullPointerException
	at org.apache.dubbo.demo.consumer.comp.DemoServiceComponent.sayHello(DemoServiceComponent.java:40)
	at org.apache.dubbo.demo.consumer.Application.main(Application.java:37)
```
Pls. provide [GitHub address] to reproduce this issue.

### Expected Result
期待的结果是调用 sayHello

```
Just put your stack trace here!
```

**Comment by huyunhaode** [comment] 2021-02-22 20:17
I can't reproduce this issue in my environment.According to the appearance of NullPointerException of the method "sayHello" of DemoServiceComponent,it seems like it is a problem that you can't get a bean named "demoServiceComponent" from the Spring container.
You can try following steps:
      1.check if the maven dependency of spring in the external libarary ,mine is 5.2.8.If your version is wrong,maybe it is  a bug of ide.And you can try to refresh the maven.
      2.you can set a breakpoint after the consumer invoke the method sayHello,and put your debug stack trace here.

**Comment by bestpayAmes** [comment] 2021-02-25 01:20
your zookeeper version is too hign,dubbo 's zk client version is 3.4.13

**Comment by LaurenceLiZhixin** [comment] 2021-03-16 09:24
I tried using 3.4.13/3.4.14 with jdk15,  and it stills problem as above. 
I tried using zookeeper 3.4.3, and it works!

**Comment by CrazyHZM** [comment] 2021-12-24 05:29
The above answer should solve your problem, temporarily close the issue, if there is still a problem, you can reopen it

**Closed by CrazyHZM** 2021-12-24 05:29 UTC
Labels: related/zookeeper
