### ISSUE TITLE
Method config does not consider overload

### ISSUE THREAD

**Issue by tswstarplanet** [apache/dubbo#3443] opened 2019-02-08 16:01 UTC
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.x
* Operating System version: all
* Java version: all

### Steps to reproduce this issue

1.Define an interface that have multiple methods with the same name and different argument types.
2.Config every overload method with different parameters.
3.Methods configed later will overwrite the previously configed method.

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by chickenlj** [comment] 2019-02-18 07:25
> 2.Config every overload method with different parameters.

How did you do that? can you provide your config snippet?

It's a known problem, do you have any thoughts on how to support method override?

**Comment by tswstarplanet** [comment] 2019-02-20 17:46
@chickenlj  I am sorry. I am busy recently. I have not started to develop for this. 
I think we can add a extra config subelement to the <dubbo:method>, such as argumentClass.
If a <dubbo:method> is configed and the method is an override method, the argumentClass is required.
And it is optional for a non-override method.

**Comment by OLPMO** [comment] 2019-09-04 07:42
@tswstarplanet Can you provide a sample to reproduce this bug?

**Comment by zhouhaopeng** [comment] 2020-04-03 04:56
1.Define an interface that have multiple methods with the same name and different argument types.
public interface DemoService {

    String sayHello(String name);

    String sayHello(Integer name);
}
2.Config every overload method with different parameters.
    @Reference(methods = {@Method(name = "sayHello", retries = 2),@Method(name = "sayHello",retries = 3)})
    private DemoService demoService;
3、in the ReferenceConfig.init() method.the method parameters retries will be overwrited to 3
if (CollectionUtils.isNotEmpty(getMethods())) {
            attributes = new HashMap<>();
            for (MethodConfig methodConfig : getMethods()) {
                AbstractConfig.appendParameters(map, methodConfig, methodConfig.getName());
                String retryKey = methodConfig.getName() + ".retry";
                if (map.containsKey(retryKey)) {
                    String retryValue = map.remove(retryKey);
                    if ("false".equals(retryValue)) {
                        map.put(methodConfig.getName() + ".retries", "0");
                    }
                }
                AsyncMethodInfo asyncMethodInfo = AbstractConfig.convertMethodConfig2AsyncInfo(methodConfig);
                if (asyncMethodInfo != null) {
//                    consumerModel.getMethodModel(methodConfig.getName()).addAttribute(ASYNC_KEY, asyncMethodInfo);
                    attributes.put(methodConfig.getName(), asyncMethodInfo);
                }
            }
        }

**Comment by changfubai** [comment] 2021-09-26 13:22
I'll try it.

**Comment by CrazyHZM** [comment] 2021-10-29 23:19
@changfubai 
Any progress ?

**Comment by chickenlj** [comment] 2021-12-16 05:51
I will close this issue since Dubbo essentially does not support method override.

> @Reference(methods = {@Method(name = "sayHello", retries = 2),@Method(name = "sayHello",retries = 3)})
private DemoService demoService;

We recommend using Annotation to meet the minimum requirement and using `dubbo.properties` as a supplement for complex configurations like method level configuration.

**Closed by chickenlj** 2021-12-16 05:51 UTC
Labels: type/bug, help wanted, level/medium
