### ISSUE TITLE
consul registe service mata map's value length limit 512

### ISSUE THREAD

**Issue by tandanzZ** [apache/dubbo#3805] opened 2019-04-04 05:56 UTC
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1
* Operating System version: mac os 10.14.4
* Java version: 1.8

### Steps to reproduce this issue

1. Spring Boot Dubbo Consul start

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
java.lang.IllegalStateException: Failed to register dubbo://192.168.0.184:20880/com.ejlerp.cache.api.HashCacher?anyhost=true&application=ejlerp-cache-provider&application.version=master&bean.name=providers:dubbo:com.ejlerp.cache.api.HashCacher:0.1&default.deprecated=false&default.dynamic=false&default.register=true&default.retries=0&default.timeout=6000&deprecated=false&dubbo=2.0.2&dynamic=false&generic=false&interface=com.ejlerp.cache.api.HashCacher&methods=hasKey,keys,values,increment,del,expireAt,delete,ttl,put,exist,entries,size,get,putAll,expire,putIfAbsent&organization=egenie&owner=dani&pid=11049&register=true&release=2.7.1&revision=10.0.0-SNAPSHOT&side=provider&threadpool=cached&timestamp=1554355820115&version=0.1 to registry 192.168.0.230:8500, cause: OperationException(statusCode=400, statusMessage='Bad Request', statusContent='Invalid Service Meta: Couldn't load metadata pair ('url', 'dubbo://192.168.0.184:20880/com.ejlerp.cache.api.HashCacher?anyhost=true&application=ejlerp-cache-provider&application.version=master&bean.name=providers:dubbo:com.ejlerp.cache.api.HashCacher:0.1&default.deprecated=false&default.dynamic=false&default.register=true&default.retries=0&default.timeout=6000&deprecated=false&dubbo=2.0.2&dynamic=false&generic=false&interface=com.ejlerp.cache.api.HashCacher&methods=hasKey,keys,values,increment,del,expireAt,delete,ttl,put,exist,entries,size,get,putAll,expire,putIfAbsent&organization=egenie&owner=dani&pid=11049&register=true&release=2.7.1&revision=10.0.0-SNAPSHOT&side=provider&threadpool=cached&timestamp=1554355820115&version=0.1'): Value is too long (limit: 512 characters)')
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:244)
	at org.apache.dubbo.registry.consul.ConsulRegistry.register(ConsulRegistry.java:90)
	at org.apache.dubbo.registry.integration.RegistryProtocol.register(RegistryProtocol.java:160)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:194)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:106)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:55)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:61)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:559)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:417)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:375)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:337)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:319)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:113)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:59)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:886)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230)
	at com.ejlerp.cache.CacheProvider.main(CacheProvider.java:20)
Caused by: com.ecwid.consul.v1.OperationException: OperationException(statusCode=400, statusMessage='Bad Request', statusContent='Invalid Service Meta: Couldn't load metadata pair ('url', 'dubbo://192.168.0.184:20880/com.ejlerp.cache.api.HashCacher?anyhost=true&application=ejlerp-cache-provider&application.version=master&bean.name=providers:dubbo:com.ejlerp.cache.api.HashCacher:0.1&default.deprecated=false&default.dynamic=false&default.register=true&default.retries=0&default.timeout=6000&deprecated=false&dubbo=2.0.2&dynamic=false&generic=false&interface=com.ejlerp.cache.api.HashCacher&methods=hasKey,keys,values,increment,del,expireAt,delete,ttl,put,exist,entries,size,get,putAll,expire,putIfAbsent&organization=egenie&owner=dani&pid=11049&register=true&release=2.7.1&revision=10.0.0-SNAPSHOT&side=provider&threadpool=cached&timestamp=1554355820115&version=0.1'): Value is too long (limit: 512 characters)')
	at com.ecwid.consul.v1.agent.AgentConsulClient.agentServiceRegister(AgentConsulClient.java:278)
	at com.ecwid.consul.v1.agent.AgentConsulClient.agentServiceRegister(AgentConsulClient.java:265)
	at com.ecwid.consul.v1.ConsulClient.agentServiceRegister(ConsulClient.java:305)
	at org.apache.dubbo.registry.consul.ConsulRegistry.doRegister(ConsulRegistry.java:95)
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:231)
```

**Comment by ettingshausen** [comment] 2020-03-26 01:58
Any updates ?

**Comment by gaoxinge** [comment] 2020-04-08 05:56
I guess there is no update for this problem. @tandanzZ @ettingshausen 

## problem

The problem arises from that 

- consul registry only allows [512 bytes meta value length](https://github.com/hashicorp/consul/blob/aae14b39514d7d4e0537d35308d6959f35bfbc48/agent/structs/structs.go#L97)
- consul registry in dubbo registers a too long url in meta which exceeds 512 bytes

## url in meta

The url in meta is produced by the following code: 

https://github.com/apache/dubbo/blob/317e62f73fd0a9bac4b34eb8b2c31bbae591ef91/dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulRegistry.java#L278

And `url.toFullString` will add the whole params to the final string:

https://github.com/apache/dubbo/blob/317e62f73fd0a9bac4b34eb8b2c31bbae591ef91/dubbo-common/src/main/java/org/apache/dubbo/common/URL.java#L1295

https://github.com/apache/dubbo/blob/317e62f73fd0a9bac4b34eb8b2c31bbae591ef91/dubbo-common/src/main/java/org/apache/dubbo/common/URL.java#L1338

So if you use too many parameters, you will reproduce the problem.

## solution (maybe)

Becasuse dubbo uses `UrlUtils.isMatch` to check whether consumerUrl equals to the providerUrl:

https://github.com/apache/dubbo/blob/317e62f73fd0a9bac4b34eb8b2c31bbae591ef91/dubbo-common/src/main/java/org/apache/dubbo/common/utils/UrlUtils.java#L393-L422 

and this function only use `Interface`, `CATEGORY_KEY`, `ENABLED_KEY`, `GROUP_KEY`, `VERSION_KEY`, `CLASSIFIER_KEY` in url to compare.

So consul register in dubbo can only register these five elements in registry instead using `url.toFullString` to register the whole url.

## someone may help

@beiwei30 @chickenlj @Moriadry

**Comment by ettingshausen** [comment] 2020-04-08 06:39
Yeah, I have to split the services and rename the method name with shorter name, it should work. But the host name may change due to different server, and it may more than 512 characters again.
The count of methods in an interface  have to stay within a small number to keep the full URI less than 512 characters which is hard.
If this problem is not solved, consul as a registration center is not practical.

**Comment by gaoxinge** [comment] 2020-04-09 13:18
@tandanzZ @ettingshausen In version 2.7.x, dubbo introduces the `metadata center` and `config center` which aim to release the pressure of the registry center. So I think this can help us to solve the problem.

## how to solve the problem

- Firstly, we can set `simplified` to `true` in [dubbo registry attributes](http://dubbo.apache.org/en-us/docs/user/references/xml/dubbo-registry.html) to make consul store a shorter url in meta. 

    - xml configurations like this
       ```xml
       <dubbo:registry address="consul://127.0.0.1:8500" simplified="true" />
       ```

    - api configuration like this 
       ```java
       RegistryConfig registryConfig = new RegistryConfig();
       registryConfig.setAddress("consul://127.0.0.1:8500");
       registryConfig.setSimplified(true);
       ```

- Secondly, we can use the `metadata center` and `config center` to store the information of the parameters in url. This is an optional way, and we can skip this step.

## reference

- [Dubbo2.7 三大新特性详解](https://www.cnkirito.moe/dubbo27-features/)
- [一文聊透 Dubbo 元数据中心](https://www.cnkirito.moe/dubbo-metadata/)

**Comment by CrazyHZM** [comment] 2021-10-12 12:27
The above answer should solve your problem, temporarily close the issue, if there is still a problem, you can reopen it

**Closed by CrazyHZM** 2021-10-12 12:27 UTC
