### ISSUE TITLE
dubbo内存泄露

### ISSUE THREAD

**Issue by whaon** [apache/dubbo#7554] opened 2021-04-15 05:11 UTC
版本：spring-cloud-starter-dubbo 2.2.3.RELEASE，对应的dubbo版本为2.7.8，nacos的starter也是 2.2.3.RELEASE

jmap发现有个dto占用大量空间，得不到释放
手动触发几次gc仍然不能释放
![image](https://user-images.githubusercontent.com/2542483/114816968-bf762b00-9deb-11eb-84de-bf58620898ca.png)

dump后使用mat分析疑似内存泄露
![image](https://user-images.githubusercontent.com/2542483/114810491-cba7bb80-9dde-11eb-8127-2f1fb84866af.png)
![image](https://user-images.githubusercontent.com/2542483/114810506-d1050600-9dde-11eb-8f83-59dca7607962.png)
![image](https://user-images.githubusercontent.com/2542483/114810551-ea0db700-9dde-11eb-86db-9abb60baf38e.png)
![image](https://user-images.githubusercontent.com/2542483/114817084-f8160480-9deb-11eb-88f7-dcb45c28c17d.png)

猜测是rpc调用后，dto对象放到threadlocal里，然后没有释放

**Comment by whaon** [comment] 2021-04-25 06:21
> can you provider a demo to reproduce ?

i don't find the reason
it present casually

**Comment by xiaoheng1** [comment] 2021-04-25 06:35
> > can you provider a demo to reproduce ?
> 
> i don't find the reason
> it present casually

I mean to trouble you to provide a demo to reproduce this problem. Let me also check what caused it.
Because the problem you mentioned did not appear on my side.

**Comment by AlbumenJ** [comment] 2021-05-17 14:13
Internal Thread Local will hold the reference of invocation until invoke finished. Please check if there are a lot pending request.

**Comment by sahalagh** [comment] 2021-09-14 07:27
我也遇到了相同的问题, 是不是参数有大对象, 不知道哪个版本解决了这个问题. 试过2.7.13还有同样的问题

**Comment by CrazyHZM** [comment] 2021-09-28 11:58
I have not received feedback for a long time, so I will close the issues temporarily. If there are any problems, I can open the issues at any time.

**Closed by CrazyHZM** 2021-09-28 11:58 UTC
Labels: type/question

**Comment by hongyu-zxj** [comment] 2022-04-18 10:49
2.7.10 版本还是存在该问题，我可以复现

**Comment by CrazyHZM** [comment] 2022-04-18 11:37
@hongyu-zxj 
Does it still exist in the latest version 2.7.15

**Comment by hongyu-zxj** [comment] 2022-04-24 01:18
> 

能说一下，2.7.15具体是在哪里修复的吗？

**Comment by hongyu-zxj** [comment] 2022-04-24 01:24
> @hongyu-zxj Does it still exist in the latest version 2.7.15
@CrazyHZM 能说一下之前的版本具体的问题是什么吗？在哪里做了修复？

**Comment by CrazyHZM** [comment] 2022-04-24 02:17
@hongyu-zxj 
我的意思是在最新的2.7.15中是否还存在这个问题？
