### ISSUE TITLE
@EnableDubbo 不搜索scanBasePackages指定目录

### ISSUE THREAD

**Issue by w548544375** [apache/dubbo#4693] opened 2019-07-30 03:02 UTC
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: MacOS Catalina 10.15 Beta
* Java version: 1.8
### project struct
![image](https://user-images.githubusercontent.com/832040/62096991-240bf200-b2b8-11e9-8d4e-c9cee2802c06.png)
### DubboConfiguration
```
@Configuration
@EnableDubbo(scanBasePackages = "com.weiguang.www.dubboprovider.service")
@PropertySource(value = "classpath:dubbo-provider.properties")
public class DubboConfiguration {

    @Bean
    public ProviderConfig providerConfig(){
        ProviderConfig providerConfig = new ProviderConfig();
        providerConfig.setTimeout(3000);
        return providerConfig;
    }

}

```
### log
```
[DUBBO] No Spring Bean annotating Dubbo's @Service was found under package[com.weiguang.www.dubboconsumer.config], dubbo version: 2.7.3, current host: 192.168.1.111
```
搜索的是config文件所在的目录，并不是 ``` @EnableDubbo(scanBasePackages = "com.weiguang.www.dubboprovider.service") ``` 指定的目录。

导致在zookeeper中,provider内容为空，
```
[zk: 127.0.0.1:2181(CONNECTED) 0] ls /
[dubbo, zookeeper]
[zk: 127.0.0.1:2181(CONNECTED) 1] ls /dubbo
[com.weiguang.www.dubbointerface.service.HelloService]
[zk: 127.0.0.1:2181(CONNECTED) 2] ls /dubbo/com.weiguang.www.dubbointerface.service.HelloService
[configurators, consumers, providers, routers]
[zk: 127.0.0.1:2181(CONNECTED) 3] ls /dubbo/com.weiguang.www.dubbointerface.service.HelloService/providers
[]
[zk: 127.0.0.1:2181(CONNECTED) 4] 
```
最终导致consumer 调用时出现 No provider availabe 错误:
``` 
    "timestamp": "2019-07-30T02:39:07.740+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "No provider available from registry 127.0.0.1:2181 for service com.weiguang.www.dubbointerface.service.HelloService:1.0.0 on consumer 192.168.1.111 use dubbo version 2.7.3, please check status of providers(disabled, not registered or in blacklist).",
    "path": "/hello"
```
### 解决方法：
需要在configuration类上加注解 ```@DubboComponentScan(basePackages = "com.weiguang.www.dubboprovider.service") ``` ，service才会被注册。

**Comment by mercyblitz** [comment] 2019-07-30 08:22
Which version of Spring Framework your application used?

If version > 4.2, it works, because of `@Alias` was introduced since Spring Framework 4.2.

**Comment by mercyblitz** [comment] 2019-07-30 08:26
Please notice the JavaDoc of `@EnableDubbo` :

```java
Enables Dubbo components as Spring Beans, equals DubboComponentScan and EnableDubboConfig combination.
Note : EnableDubbo must base on Spring Framework 4.2 and above
```

Or reference the test case of `@EnableDubbo` :
https://github.com/apache/dubbo/blob/master/dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/context/annotation/EnableDubboTest.java#L152

**Comment by w548544375** [comment] 2019-07-30 10:17
@mercyblitz  
```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.6.RELEASE</version>
        <relativePath/>
    </parent>
```
and i found that the spring version in is 5.1.8.RELEASE.

**Comment by w548544375** [comment] 2019-07-30 10:34
```
@Configuration
@EnableDubbo(scanBasePackages = {"com.weiguang.www.dubboprovider.service"})
@PropertySource(value = "classpath:dubbo-provider.properties")
public class DubboConfiguration {

    @Bean
    public ProviderConfig providerConfig(){
        ProviderConfig providerConfig = new ProviderConfig();
        providerConfig.setTimeout(3000);
        return providerConfig;
    }

}
```
as i configured,i started up application in debug mode,and the ``` basePackages``` is an empty value.
![image](https://user-images.githubusercontent.com/832040/62122197-bbdd0080-b2f7-11e9-9038-48d06a447976.png)
@mercyblitz

**Comment by ll2lxl** [comment] 2019-08-01 10:00
only scan the EnableDubbo directory and its subdirectories,and alisfor does not take effect

**Comment by beiwei30** [comment] 2019-08-22 03:50
@ll2lxl @jasonjoo2010 would you mind to take a look at https://github.com/apache/dubbo-samples/commit/7e25d4e2e144ca3ff11da134385857a1828f6089? I cannot reproduce the issue.

**Comment by cvictory** [comment] 2019-09-04 03:46
@w548544375  what about this issue ?

**Comment by cvictory** [comment] 2019-09-04 06:28
I will close this issue . If you still have some problem, please reopen this issue.

**Closed by cvictory** 2019-09-04 06:28 UTC

**Comment by jasonjoo2010** [comment] 2019-09-04 06:36
@cvictory Please refer to #4895 

And there is reproduction project in comment
