### ISSUE TITLE
指定版本号问题

### ISSUE THREAD

**Issue by HuShao96** [apache/dubbo#7847] opened 2021-05-24 02:42 UTC
项目a是消费者。指定消费提供者version：1.0.0；@DubboReference(version = "1.0.0")
项目b是提供者，分别启动两个服务
version：1.0.0:

```
server:
  port: 6201
dubbo:
  protocols:
    dubbo:
      name: dubbo
      port: -1
  provider:
    version: '1.0.0'
spring:
  application:
    name: flow-process-center
version:2.0.0:
```

```
server:
  port: 6202
dubbo:
  protocols:
    dubbo:
      name: dubbo
      port: -1
  provider:
    version: '2.0.0'
spring:
  application:
    name: flow-process-center
```
；
但是项目a还是会轮训调用项目b的两个不同版本的服务；
spring cloud alibaba 2021.1+dubbo;
![image](https://user-images.githubusercontent.com/26806329/119289260-d7f42380-bc7c-11eb-9d65-9bdd58ea3bea.png)

**Comment by plusmancn** [comment] 2021-05-24 07:21
Duplicate of #7817

**Comment by HuShao96** [comment] 2021-05-24 07:24
> #7817的重复
> 
> 请提供杜博的版本。

nacos2.0.1

**Comment by HuShao96** [comment] 2021-05-24 07:24
> Duplicate of #7817
> 
> @HuShao96 Please provide the version of Dubbo.

dubbo2.7.8

**Comment by plusmancn** [comment] 2021-05-25 08:35
@HuShao96 
It works for me on Dubbo both 2.7.8 and 2.7.11.
Maybe you should check whether the config is effective.

Or you can provide a runnable demo application, and put the GitHub address in the comment.

**Comment by CrazyHZM** [comment] 2021-09-26 09:52
Try to solve it with the above answer, if it has not been solved, you can reopen the issues.

**Closed by CrazyHZM** 2021-09-26 09:52 UTC
