### ISSUE TITLE
Nacos 注册中心服务列表显示异常！

### ISSUE THREAD

**Issue by huhonggit** [apache/dubbo#5425] opened 2019-12-04 06:28 UTC
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version:  mac
* Java version: 1.8

### Steps to reproduce this issue

1. 服务提供者项目为A【里面接一个接口】，2个项目消费A，分别为 项目B 和项目C。
2. 服务注册到nacos 将项目名没有放在服务名上，而是放在了元数据中。导致3个项目启动  只有2个服务。分别一个提供者、一个消费者【应该是2个消费者】。
3. 2个消费者调用没有影响。列表bug

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by chickenlj** [comment] 2019-12-18 12:03
duplicate of #5426

**Closed by chickenlj** 2019-12-18 12:03 UTC
