### ISSUE TITLE
[Bug] 3.3.0-beta2 update to beta3,  exception : module java.base does not "opens java.util" to unnamed module

### ISSUE THREAD

**Issue by ZhiQinIsZhen** [apache/dubbo#14259] opened 2024-05-30 07:47 UTC
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo 3.3.0-beta3, jdk 21, windows

### Steps to reproduce this issue

```java
java.io.IOException: org.apache.dubbo.common.serialize.SerializationException: java.lang.RuntimeException: Unable to make field private final java.lang.Object[] java.util.ImmutableCollections$ListN.elements accessible: module java.base does not "opens java.util" to unnamed module @60addb54
 field: xxx.service.auth.bo.AuthUserBO.authorities
 class: xxx.service.auth.bo.AuthUserBO
```

1.It has no this exception in dubbo 3.3.0-beta2 version
2.Upgrade to dubbo 3.3.0-beta3 version, has this exception. so i add `--add-opens java.base/java.util=ALL-UNNAMED`,  has other exception
`com.alibaba.com.caucho.hessian.io.HessianFieldException: xxx.service.auth.bo.AuthUserBO.authorities: null array`

Here's my class(AuthUserBO) information
```java
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AuthUserBO implements Serializable {
    @Serial
    private static final long serialVersionUID = 6046110472442516409L;

    /**
     * 权限列表
     */
    private List<AuthGrantedAuthorityBO> authorities = new ArrayList<>();
}
```
3.i update AuthUserBO code to this 
```java
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AuthUserBO implements Serializable {
    @Serial
    private static final long serialVersionUID = 6046110472442516409L;

    /**
     * 权限列表
     */
    private List<AuthGrantedAuthorityBO> authorities;
}
```
then use set method : authUserBO.setAuthorities (new ArrayList<>()), it has no exception.
Last i remove vm  `--add-opens java.base/java.util=ALL-UNNAMED`, it alse has no exception.

### What you expected to happen

no exception

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aofall** [comment] 2024-05-31 06:19
In 3.3.0-beta.2 the default serialization is fastjson2, in 3.3.0-beta.3 the hessian serialization back and set as default serialization by #13974 

It caused by hessian serialization. You can temporarily set the serialization as fastjson2 again. The issue of hessian serialization with newly JDK may solved in the future.

You can modify the settings according to the actual situation, and be aware that there may be unexpected issues with fastjson2 as well.

```
dubbo:
  protocol:
    serialization: fastjson2
    prefer-serialization: fastjson2,hessian2
```

**Comment by wcy666103** [comment] 2024-06-05 03:06
We had a meeting to discuss this problem, the reason is that the adaptation of hessian2 with high jdk version is difficult, so we can use fastjson2 first

**Comment by AlbumenJ** [comment] 2024-06-10 07:44
Already fixed in https://github.com/apache/dubbo-hessian-lite/pull/70

Please wait Hessian Lite 4.0.1 and Dubbo 3.3.0-beta.4 being released. BTW, in order to solve it, you need to upgrade both client and server side.

**Closed as completed by AlbumenJ** 2024-06-10 07:44 UTC
Labels: type/need-triage, component/need-triage
