### ISSUE TITLE
Use the echo test to throw a ClassCastException

### ISSUE THREAD

**Issue by kiwiflydream** [apache/dubbo#5074] opened 2019-09-17 07:04 UTC
### Environment

* Dubbo version: 2.7.3
* Operating System version: mac
* Java version: 1.8

### Steps to reproduce this issue
```
@Service
public class DubboEchoService {

    @Reference(version="1.0.0")
    private DemoService demoService;

    public void test(){
        EchoService echoService = (EchoService) demoService;
        Object status = echoService.$echo("OK");
        System.out.println(status);
    }
}
```

```
java.lang.ClassCastException: com.sun.proxy.$Proxy55 cannot be cast to org.apache.dubbo.rpc.service.EchoService
```

I found all the examples were through  <dubbo:reference />
, but we have no XML file in spring boot and can only use the annotation, but found the error

**Comment by CodingSinger** [comment] 2019-09-19 06:26
yes, it's a bug, because the annotation processor only use the DemoService as the proxy interface. we will fix it soon.

**Comment by kiwiflydream** [comment] 2019-09-19 06:36
Thanks.

**Comment by Leishunyu** [comment] 2019-10-14 08:52
I did not reproduce this problem.

**Comment by hhofchina** [comment] 2019-12-20 01:46
reproduce: annotation config dubbo 

        Assert.assertEquals("OK", ((EchoService) yourDubboService).$echo("OK"));

class com.sun.proxy.$Proxy106 cannot be cast to class org.apache.dubbo.rpc.service.EchoService (com.sun.proxy.$Proxy106 and org.apache.dubbo.rpc.service.EchoService are in unnamed module of loader 'app')

**Comment by changfubai** [comment] 2021-09-26 12:53
I did not reproduce on master, I guess it has been fixed.
may @CrazyHZM  close it ?

**Closed** 2021-09-26 14:12 UTC
Labels: type/bug, help wanted, level/easy, version/2.7.x
