### ISSUE TITLE
Dubbo 2.7.7 @DubboReference(version = "*")注解失效

### ISSUE THREAD

**Issue by sarins** [apache/dubbo#6391] opened 2020-06-30 09:21 UTC
- [*] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [*] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: macOS Mojave 10.14.6
* Java version: 1.8.x

### Steps to reproduce this issue

1. 升级 dubbo 到 2.7.7
2. 使用 @DubboReference(version = "*") 注解注入Dubbo服务
3. 服务提供者侧一直保持为2.7.7版本

### Expected Result

此时被注入的dubbo服务应该可以使用。

### Actual Result

被注入的Dubbo服务不能被使用（经验证消费者侧降级至2.7.6时，服务可用）

```

**Comment by sarins** [comment] 2020-06-30 09:23
@mercyblitz

**Comment by skyguard1** [comment] 2020-07-02 07:30
I've reproduced the problem, and here's the stack trace:
[02/07/20 15:23:48:168 CST] DubboServerHandler-10.161.112.38:20880-thread-3  INFO dubbo.CallbackServiceCodec:  [DUBBO] Not found exported service: org.apache.dubbo.demo.DemoService:*:20880 in [org.apache.dubbo.demo.DemoService:20880], may be version or group mismatch , channel: consumer: /10.161.112.38:54217 --> provider: /10.161.112.38:20880, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[], attachments={input=240, path=org.apache.dubbo.demo.DemoService, remote.application=dubbo-demo-annotation-consumer, dubbo=2.0.2, interface=org.apache.dubbo.demo.DemoService, version=*}], dubbo version: , current host: 10.161.112.38
org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.demo.DemoService:*:20880 in [org.apache.dubbo.demo.DemoService:20880], may be version or group mismatch , channel: consumer: /10.161.112.38:54217 --> provider: /10.161.112.38:20880, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[], attachments={input=240, path=org.apache.dubbo.demo.DemoService, remote.application=dubbo-demo-annotation-consumer, dubbo=2.0.2, interface=org.apache.dubbo.demo.DemoService, version=*}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:265)
	at org.apache.dubbo.rpc.protocol.dubbo.CallbackServiceCodec.decodeInvocationArgument(CallbackServiceCodec.java:289)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:165)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:80)
	at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:57)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:44)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I wonder if that's your question,it looks like a bug,If version is configured *, there  is a problem

**Comment by skyguard1** [comment] 2020-07-02 07:38
@chickenlj I found that I commited the following code on February 20, 2020. When the version is *, the service cannot be normally exposed. Please confirm whether it is a problem, if so, I can submit pr to fix this bug:

private String createServiceKey(String serviceName, String serviceVersion, int port) {
        StringBuilder buf = new StringBuilder();
        if (StringUtils.isNotEmpty(serviceGroup)) {
            buf.append(serviceGroup).append('/');
        }

        buf.append(serviceName);
        if (StringUtils.isNotEmpty(serviceVersion) && !"0.0.0".equals(serviceVersion)) {
            buf.append(':').append(serviceVersion);
        }
        buf.append(':').append(port);
        return buf.toString();
    }

**Comment by sarins** [comment] 2020-07-02 09:17
@skyguard1 cool

**Comment by CrazyHZM** [comment] 2021-03-31 00:07
Are you still concerned about this issue, if so, please submit pr to fix it, if not, this issue will be fixed in the near future.

**Comment by skyguard1** [comment] 2021-03-31 01:51
I am waiting to confirm whether this issue is a bug, I will submit pr to fix it, thanks for the reply

**Closed** 2021-04-06 07:20 UTC
